# Header
mail_icon: fa-envelope-o

# Content
excerpt_link: Read More
fancybox: true

#your personal image
# your_img: holder.js/150x150
your_img: prof.png

# Miscellaneous
google_analytics: 
favicon:
twitter:
google_plus:
fb_admins:
fb_app_id: